### ISSUE TITLE
Is anybody still maintaining this?

### ISSUE THREAD

**Issue by Luapulu** [mppmu/MJDSigGen.jl#4]
We're using MJDSigGen.jl for our work and I was wondering if anybody is still maintaining this code. We have some patches we might want to open merge requests for.

**Comment by oschulz** [comment]
Hi Paul,

I wasn't aware that MJDSigGen was being used by anyone outside of our group/collaboration. We've developed a new, pure-Julia package for germanium detector simulation, https://github.com/JuliaPhysics/SolidStateDetectors.jl, and it's now mature enough that we haven't used MJDSigGen a lot lately.

However, the package isn't abandoned, it just hasn't receive a lot of maintenance for a while. But if there's interest, PRs are very welcome. We should also probably merge in some recent upstream code (from https://github.com/radforddc/icpc_siggen).

**Comment by Luapulu** [comment]
Hi, thanks for the reply. I'm doing my bachelor thesis at TUM E15 (Prof. Schönert). We're using your wrapper :).
