### ISSUE TITLE
`with_group_effects` convenience function

### ISSUE THREAD

**Issue by Luapulu** [mppmu/MJDSigGen.jl#7]
At some point I wasted a few days of compute time because I had accidentally left diffusion, acceleration and repulsion on when I didn't mean to. Since then I turn group effects off in my configs, so the config really only defines the geometry, impurities, etc. and I configure group effects in the code (see following example), because turning them on or off tends to be part of the logic of the code, rather than a preset config that stays constant.

```julia
result = with_group_effects(setup, E, cloud_size) do stp
    # do something with the stp, using group effects
    return result
end
```

For people who usually need group effects but sometimes turn it off, I can also add another method like so:

```julia
result = with_group_effects(:off, setup) do stp
    # do something with the stp, not using group effects
    return result
end
```

This way, people can turn it `:off` or `:on`.

If there's interest, I can make a pull request and add it in. May be in utils.jl?

**Comment by oschulz** [comment]
Sure, sounds good!

**Comment by Luapulu** [comment]
Added in #8.
